name: The Qlog
url: "http://blog.quyi.de"
author: Yi Qu

markdown: kramdown
permalink: /:year/:title/
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page/:num/"

links:
  - name: 关于
    url: /about/
  - name: 目录
    url: /archives/
  - name: 订阅
    url: /feed.xml

social:
  - name: Email
    url: "mailto:rangerqu@gmail.com"
  - name: Twitter
    url: "https://twitter.com/rangerqu"
  - name: GitHub
    url: "https://github.com/rangerqu"

google_analytics: UA-5424359-4
disqus: quyide